### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by annaversee** [PRO100KatYT/FortniteResponseDumper#10]
Authentication no longer works
{"redirectUrl":"https://localhost/launcher/authorized","authorizationCode":null,"exchangeCode":null,"sid":null,"ssoV2Enabled":true}

**Comment by PRO100KatYT** [comment]
It looks like you are not authenticated on the epic games website in your browser. Choose the second option when the program asks `Are you logged into your Epic account that you would like the program to use in your browser?`, log in there and paste the authorization code into the program.

**Comment by annaversee** [comment]
odd that it works now because a few weeks ago it didn't at all even though I was logged in. I'm unaware if the EOS is sometimes having issues but thank you for responding none the less.<3
