### ISSUE TITLE
id of a use

### ISSUE THREAD

**Issue by vendentwjwbx** [PRO100KatYT/FortniteResponseDumper#2]
hello I wanted to know if you could make me a code in python just to have the id of a user and his external account associated THANK YOU

**Comment by PRO100KatYT** [comment]
To obtain a specific player’s account ID, you can use the “Anyone’s STW profile dumper” feature of the program to dump their profiles. Then, by opening one of the profiles, you will find a JSON object labeled “accountId” on line 7.
I am currently unaware of how to obtain information about associated external accounts for other players.

**Comment by vendentwjwbx** [comment]
I found myself how I could do but you would not know how I can find their
epic games username with the external account

Le sam. 15 juil. 2023 à 18:44, PRO100KatYT ***@***.***> a
écrit :

**Comment by vendentwjwbx** [comment]
it's all good I managed to code it myself with fornite api, thank you for your help and your code
