### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Ch1lly5** [PRO100KatYT/FortniteResponseDumper#4]
Hello, is there a version of this with smaller / easier code that only looks up other players files? There is a version on pull requests that is very nice but it only does the logged in accounts info and requires an auth code each run

**Comment by PRO100KatYT** [comment]
You might be looking for this particular part of this program:

```python
# The Anyone's StW Profile Dumper part of the program.
def anyonesStWProfileDumper():
    # Get the account id using displayname.
    nameInput = input("Insert the epic games display name of the account whose Save the World profiles you'd want the program to save:\n")
    if not nameInput: print(f"You didn't input anything.\n"); return
    print(); login()
    reqGetAccountId = json.loads(session.get(links.getAccountIdByName.format(nameInput), headers=vars.headers, data="{}").text)
    if "errorMessage" in reqGetAccountId:
        print(f"ERROR: {reqGetAccountId['errorMessage']}. Please try again with a different username.\n"); return
    accountId, displayName = [reqGetAccountId['id'], reqGetAccountId['displayName']]

    publicProfilePath, publicProfilesList = [os.path.join(vars.path, f"{displayName}'s STW Profiles"), ["campaign", "common_public", "profile0"]]  # profile0 has to be after campaign and common_public since the program is going to recreate it using them.
    if not os.path.exists(publicProfilePath): os.makedirs(publicProfilePath)

    # Get and dump the profiles.
    profilesWord, haveWord = ["profiles", "have"]
    if len(publicProfilesList) == 1: profilesWord, haveWord = ["profile", "has"]
    print(f"Dumping {len(publicProfilesList)} {displayName}'s Save the World {profilesWord}...\n")
    dumpProfiles(publicProfilesList, ["campaign", "common_public"], publicProfilePath, accountId, "public", "QueryPublicProfile")
    print(f"\n{displayName}'s Save the World {profilesWord} {haveWord} been successfully saved in {publicProfilePath}.\n")
```

**Comment by Ch1lly5** [comment]
Hello, there was a user that updated this code however missed out the token login part (requiring you to supply a new auth every time now) and dumping another users profile (it only dumps the auths profile). Ill attach the link below, i was wondering if you knew about it / had a fix with these changes in? This code is great for using however terrible for modifying haha.

https://github.com/PRO100KatYT/FortniteResponseDumper/pull/1/commits/7c59f9a807aa6f1deb77322faf3a1894f8b270c7

**Comment by PRO100KatYT** [comment]
You can take a look at my old program [Anyone's STW profile dumper](https://github.com/PRO100KatYT/AnyonesSTWProfileDumper/tree/44d07f21b91a6e54bebbd8fa6aeb572ef982765d) which I merged into the Response Dumper. It only contains dumping other players' profiles.
