### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by JuniorzGTX** [PRO100KatYT/FortniteResponseDumper#6]
cmd closes after inputting the auth code

**Comment by PRO100KatYT** [comment]
I have just tested the program and inputting the auth code works for me. What operating system are you on? If you are on Windows, then to see the python crash report you can launch the program via cmd using `python <pathToFIle>` and send the crash report here.

**Comment by JuniorzGTX** [comment]
issue fixed itself somehow
