### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by NotTacs** [PRO100KatYT/FortniteResponseDumper#8]
![image](https://github.com/PRO100KatYT/FortniteResponseDumper/assets/142945024/9e373a4b-f76d-4b75-8b17-ce9cc61e6888)

**Comment by PRO100KatYT** [comment]
For now, set the Dump_Friendlists value to false in the config.ini file. I'll add a fix for this bug in the upcoming update.

**Comment by NotTacs** [comment]
Thank you
